import {
  FiHome,
  FiGrid,
  FiCalendar,
  FiTrendingUp,
  FiShoppingBag,
  FiShoppingCart,
  FiCpu,
  FiSettings,
  FiUser,
  FiTag,
  FiPlusCircle,
  FiInbox,
  FiCheckCircle,
  FiCloudDrizzle,
  FiSun,
  FiClock,
  FiUmbrella,
  FiAlertTriangle,
  FiBarChart2,
  FiDroplet,
  FiLayers,
  FiFileText,
  FiMapPin,
  FiThermometer,
  FiHeart,
  FiColumns,
  FiUsers,
  FiVideo,
  FiMessageCircle,
  FiStar,
  FiPackage,
  FiNavigation,
  FiList,
  FiMap,
  FiBell,
  FiCreditCard,
  FiAward,
  FiBriefcase,
  FiBox,
  FiShield,
  FiLogIn,
  FiUserPlus,
  FiInfo,
  FiMail,
} from 'react-icons/fi';

export const PUBLIC_NAV = [
  { label: 'Home', to: '/', icon: FiHome, end: true },
  { label: 'Features', to: '/features', icon: FiGrid },
  { label: 'Agriculture Store', to: '/agriculture-store', icon: FiShoppingCart },
  { label: 'Marketplace', to: '/marketplace', icon: FiShoppingBag },
  { label: 'Weather', to: '/weather', icon: FiCloudDrizzle },
  { label: 'Mandi Prices', to: '/mandi-prices', icon: FiTrendingUp },
  { label: 'AI Crop Advisor', to: '/crop-recommendation', icon: FiCpu },
  { label: 'Disease Detection', to: '/disease-detection', icon: FiShield },
  { label: 'Expert Consultation', to: '/expert-consultation', icon: FiUsers },
  { label: 'About', to: '/about', icon: FiInfo },
  { label: 'Contact', to: '/contact', icon: FiMail },
  { label: 'Login', to: '/login', icon: FiLogIn, auth: true },
  { label: 'Get Started', to: '/register', icon: FiUserPlus, auth: true },
];

export const SIDEBAR_NAV_SECTIONS = [
  {
    id: 'main',
    label: 'Main',
    items: [
      { label: 'Dashboard', to: '/dashboard', icon: FiHome, end: true },
      { label: 'Field Reports', to: '/dashboard/field-reports', icon: FiGrid },
      { label: 'Crop Planner', to: '/dashboard/crop-planner', icon: FiCalendar },
      { label: 'Notifications', to: '/dashboard/notifications', icon: FiBell },
      { label: 'Market Prices', to: '/dashboard/market-prices', icon: FiTrendingUp },
      { label: 'Weather', to: '/dashboard/weather', icon: FiCloudDrizzle },
    ],
  },
  {
    id: 'weather',
    label: 'Weather',
    items: [
      { label: 'Current Weather', to: '/dashboard/weather', icon: FiSun },
      { label: 'Hourly Forecast', to: '/dashboard/weather/hourly', icon: FiClock },
      { label: '7 Day Forecast', to: '/dashboard/weather/7day', icon: FiCalendar },
      { label: 'Rain Prediction', to: '/dashboard/weather/rain', icon: FiUmbrella },
      { label: 'Weather Alerts', to: '/dashboard/weather/alerts', icon: FiAlertTriangle },
      { label: 'Weather Charts', to: '/dashboard/weather/charts', icon: FiBarChart2 },
    ],
  },
  {
    id: 'mandi',
    label: 'Mandi Prices',
    items: [
      { label: "Today's Prices", to: '/dashboard/market-prices', icon: FiTrendingUp, end: true },
      { label: 'Historical Prices', to: '/dashboard/market-prices/history', icon: FiClock },
      { label: 'Price Charts', to: '/dashboard/market-prices/charts', icon: FiBarChart2 },
      { label: 'Nearby Mandis', to: '/dashboard/market-prices/nearby', icon: FiMapPin },
      { label: 'Favourite Markets', to: '/dashboard/market-prices/favorites', icon: FiHeart },
      { label: 'Comparison', to: '/dashboard/market-prices/compare', icon: FiColumns },
    ],
  },
  {
    id: 'expert',
    label: 'Expert Consultation',
    items: [
      { label: 'Expert List', to: '/dashboard/consultation', icon: FiUsers, end: true },
      { label: 'Book Appointment', to: '/dashboard/consultation/book', icon: FiPlusCircle },
      { label: 'Appointment Calendar', to: '/dashboard/consultation/calendar', icon: FiCalendar },
      { label: 'Video Call', to: '/dashboard/consultation/video', icon: FiVideo },
      { label: 'Chat', to: '/dashboard/consultation/chat', icon: FiMessageCircle },
      { label: 'Consultation History', to: '/dashboard/consultation/history', icon: FiFileText },
      { label: 'Ratings', to: '/dashboard/consultation/ratings', icon: FiStar },
    ],
  },
  {
    id: 'insights',
    label: 'AI Insights',
    items: [
      { label: 'AI Assistant', to: '/dashboard/ai-assistant', icon: FiCpu },
      { label: 'Agro Advisories', to: '/dashboard/ai-assistant/advisories', icon: FiFileText },
      { label: 'Crop Recommender', to: '/dashboard/recommendation', icon: FiTrendingUp },
      { label: 'Buy & Sell', to: '/dashboard/bazaar', icon: FiShoppingBag },
    ],
  },
  {
    id: 'disease',
    label: 'Disease Detection',
    items: [
      { label: 'Detect Now', to: '/dashboard/disease-detection', icon: FiShield, end: true },
      { label: 'Scan History', to: '/dashboard/disease-detection/history', icon: FiFileText },
      { label: 'Treatment Library', to: '/dashboard/disease-detection/treatments', icon: FiList },
      { label: 'Pest Alerts', to: '/dashboard/disease-detection/alerts', icon: FiAlertTriangle },
    ],
  },
  {
    id: 'marketplace',
    label: 'Marketplace',
    items: [
      { label: 'My Listings', to: '/dashboard/marketplace/listings', icon: FiTag },
      { label: 'Sell Crop', to: '/dashboard/marketplace/sell', icon: FiPlusCircle },
      { label: 'Buyer Offers', to: '/dashboard/marketplace/offers', icon: FiInbox },
      { label: 'Accepted Deals', to: '/dashboard/marketplace/deals', icon: FiCheckCircle },
      { label: 'Transactions', to: '/dashboard/marketplace/transactions', icon: FiTrendingUp },
    ],
  },
  {
    id: 'soil',
    label: 'Soil Testing',
    items: [
      { label: 'Book Test', to: '/dashboard/soil', icon: FiDroplet, end: true },
      { label: 'Lab Selection', to: '/dashboard/soil/lab', icon: FiMapPin },
      { label: 'Appointment', to: '/dashboard/soil/appointment', icon: FiClock },
      { label: 'Soil Report', to: '/dashboard/soil/report', icon: FiFileText },
      { label: 'Nutrients', to: '/dashboard/soil/nutrients', icon: FiLayers },
      { label: 'pH Analysis', to: '/dashboard/soil/ph', icon: FiThermometer },
      { label: 'Fertilizer', to: '/dashboard/soil/fertilizer', icon: FiTrendingUp },
      { label: 'History', to: '/dashboard/soil/history', icon: FiCalendar },
      { label: 'Charts', to: '/dashboard/soil/charts', icon: FiBarChart2 },
    ],
  },
  {
    id: 'logistics',
    label: 'Logistics',
    items: [
      { label: 'Book Pickup', to: '/dashboard/logistics', icon: FiPackage, end: true },
      { label: 'Track Delivery', to: '/dashboard/logistics/track', icon: FiNavigation },
      { label: 'Delivery Timeline', to: '/dashboard/logistics/timeline', icon: FiList },
      { label: 'Completed Deliveries', to: '/dashboard/logistics/completed', icon: FiCheckCircle },
      { label: 'Map', to: '/dashboard/logistics/map', icon: FiMap },
    ],
  },
  {
    id: 'farmer',
    label: 'Farmer Profile',
    items: [
      { label: 'Profile', to: '/dashboard/profile', icon: FiUser, end: true },
      { label: 'Farm Details', to: '/dashboard/profile/farm', icon: FiHome },
      { label: 'Land Details', to: '/dashboard/profile/land', icon: FiMap },
      { label: 'Documents', to: '/dashboard/profile/documents', icon: FiFileText },
      { label: 'Bank Details', to: '/dashboard/profile/bank', icon: FiCreditCard },
      { label: 'Crop History', to: '/dashboard/profile/crops', icon: FiGrid },
      { label: 'Achievements', to: '/dashboard/profile/achievements', icon: FiAward },
      { label: 'Settings', to: '/dashboard/profile/settings', icon: FiSettings },
    ],
  },
  {
    id: 'admin',
    label: 'Admin Dashboard',
    items: [
      { label: 'Dashboard', to: '/dashboard/admin', icon: FiShield, end: true },
      { label: 'Users', to: '/dashboard/admin/users', icon: FiUsers },
      { label: 'Farmers', to: '/dashboard/admin/farmers', icon: FiUser },
      { label: 'Companies', to: '/dashboard/admin/companies', icon: FiBriefcase },
      { label: 'Experts', to: '/dashboard/admin/experts', icon: FiAward },
      { label: 'Products', to: '/dashboard/admin/products', icon: FiBox },
      { label: 'Orders', to: '/dashboard/admin/orders', icon: FiShoppingCart },
      { label: 'Marketplace', to: '/dashboard/admin/marketplace', icon: FiShoppingBag },
      { label: 'Reports', to: '/dashboard/admin/reports', icon: FiFileText },
      { label: 'Analytics', to: '/dashboard/admin/analytics', icon: FiBarChart2 },
      { label: 'Notifications', to: '/dashboard/admin/notifications', icon: FiBell },
      { label: 'Settings', to: '/dashboard/admin/settings', icon: FiSettings },
    ],
  },
];

export const BOTTOM_NAV_ITEMS = [
  { label: 'Home', to: '/dashboard', icon: FiHome, end: true },
  { label: 'Reports', to: '/dashboard/field-reports', icon: FiGrid },
  { label: 'AI Sathi', to: '/dashboard/ai-assistant', icon: FiCpu },
  { label: 'Market', to: '/dashboard/marketplace/listings', icon: FiTrendingUp },
  { label: 'Profile', to: '/dashboard/profile', icon: FiUser },
];